import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Orbitron } from "next/font/google";
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Design Hub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={` flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#3A1078] to-[#00867c]`}
      >
        {/* Center Card */}
        <div
          className={`${orbitron.className} group rounded-xl bg-white/10 px-6 py-10 text-white md:px-10 lg:py-14`}
        >
          {/* Logo */}
          <div className="">
            <h1 className="text-2xl font-semibold tracking-widest text-sky-300 lg:text-3xl">
              TailwindCSS{" "}
            </h1>
            <span className="bg-gradient-to-r from-pink-400 to-violet-400 bg-clip-text text-5xl font-bold text-transparent lg:text-7xl">
              Design{` `}
            </span>
            <span className="text-2xl font-semibold tracking-wider lg:text-3xl">
              Hub
            </span>
            <Link
              href={`https://github.com/Yewdev`}
              target="_blank"
              className="block py-1 text-xs tracking-widest text-white/90 lg:text-sm"
            >
              @Yewdev
            </Link>
          </div>
          {/* Divider */}
          <div className="my-10 mx-auto h-[1px] w-3/5 bg-emerald-200/40 duration-700 group-hover:w-full"></div>
          {/* Links */}
          <div className="flex max-w-[14rem] flex-col gap-6 tracking-wider lg:max-w-[26rem]">
            <Link
              href={`#`}
              className="border-l-8 pl-4 duration-500 hover:border-emerald-500 "
            >
              This is a link
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
